baseURL = 'https://ch1n3du.github.io/Ch1n3du/'
languageCode = 'en-us'
title = "pico adventures"
theme = "PaperMod"

[menu]
[[menu.main]]
identifier = "Home"
name = "Home"
url = "/home"
weight = -100
class = ""
