baseURL = 'https://ch1n3du.github.io/Ch1n3du/'
languageCode = 'en-us'
title = "pico adventures"
theme = "PaperMod"

[params]
showBreadCrumbs = true
showReadingTime = true
showShareButtons = true
showPostNavLinks = true
showCodeCopyButtons = true

[params.homeInfoParams]
Title = "Hello Stranger"
Content = "You've stumbled upon my distant shores, herein I try time and time again to fight my endless boredom."

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/ch1n3du3/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Ch1n3du"

[menu]
[[menu.main]]
identifier = "About"
name = "About me"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
